FROM rust:latest

# Set working directory
WORKDIR /app

# Copy the flow-project source code from the build-repo
COPY /flowrs-build /app

#CMD ["ls", "/app"]

# Compile the Rust project for Linux
RUN cargo build --release

# Expose the compiled dynamic library
CMD ["cp", "/app/target/release/runner_main", "/output/runner_main"]