version: "3"

services:
  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "55680:55680"
      - "55681:55681"
      - "14250:14250"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./tempo/tempo.yaml:/etc/tempo.yaml"

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    # http://localhost:3000
    image: grafana/grafana:latest
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_SECURITY_ALLOW_EMBEDDING=true"
      - "GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s"
    volumes:
      - "./grafana-provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000" # TODO: this needs to be changed for merge with flow-builder, also the references in the flow-builders iFrames
    depends_on:
      - prometheus
      - tempo